name: Validate Curated Release Notes
on:
  pull_request:
    branches:
      - main
jobs:
  validate-schema:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Validate JSON schema
        run: |
          error_count=0
          allowed_labels=("kind/bug-fix" "N/A" "kind/feature" "kind/upgrade-consideration" "kind/breaking-change" "kind/api-change" "kind/deprecation" "impact/high" "impact/medium")
          for file in addons/**/curated/**/curated-release-notes.json; do
            echo "Validating $file"
            # Extract directory version from the file path
            dir_version=$(basename "$(dirname "$file")")
            # Check if the JSON file contains required fields
            if ! jq -e '.addonName and .version and .notes' "$file" > /dev/null; then
              echo "Error: $file is missing one or more required fields (addonName, version, notes)."
              error_count=$((error_count + 1))
              continue
            fi
            # Check if 'notes' contains both 'label' and 'text', and validate them
            notes_count=$(jq '.notes | length' "$file")
            for i in $(seq 0 $((notes_count-1))); do
              note_label=$(jq -r ".notes[$i].label[]" "$file")
              note_text=$(jq -r ".notes[$i].text" "$file")
              if [ -z "$note_label" ] || [ -z "$note_text" ]; then
                echo "Error: Note entry $i in $file has an empty 'label' or 'text' field."
                error_count=$((error_count + 1))
                continue
              fi
              # Check if label is in the allowed list
              for label in $note_label; do
                if [[ ! " ${allowed_labels[@]} " =~ " $label " ]]; then
                  echo "Error: Invalid label '$label' in note entry $i of $file. Allowed labels are: ${allowed_labels[*]}."
                  error_count=$((error_count + 1))
                fi
              done
            done
            echo "$file passed all validation checks."
          done
          if [ $error_count -gt 0 ]; then
            echo "Total errors: $error_count"
            exit 1
          else
            echo "All files passed validation checks."
          fi
