name: Validate Curated Release Notes
on:
  pull_request:
    branches:
      - main

jobs:
  validate-schema:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Initialize Go module
        run: |
          cd .github/workflows
          go mod init github.com/lintercheck  # Use the repo name without any username
          go mod tidy  # Fetch any necessary dependencies

      - name: Build linter
        run: |
          cd .github/workflows
          go build -o validate-release-notes .

      - name: Run linter
        run: |
          cd .github/workflows
          ./validate-release-notes  # Run the Go linter binary
